name: dawn_dev
description: A Dawn app
publish_to: none
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  dawn: ^6.0.0
  js: ^0.6.4
dev_dependencies:
  build_runner: ^2.2.1
  build_web_compilers: ^3.2.6
  dawn_lints: ^3.0.0
