name: dawn_dev
description: A Dawn app
publish_to: none
environment:
  sdk: ">=2.19.4 <3.0.0"
dependencies:
  dawn: ^7.0.2
  js: ^0.6.7
dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  dawn_lints: ^3.1.0
